#!/bin/bash
# Wrapper para correr los comandos al estilo `git comando parametros`
# Hay que crearlos en libdir/lvpn-comando

# ENV
# Tomar las variables de entorno (por ejemplo de un archivo de configuración
# o de la shell) o usar directorios locales
TINC=${TINC:-/etc/tinc/lvpn}
LVPN="$(readlink -f $0)"
LVPN_DIR="${LVPN_DIR:-$(dirname "$LVPN")}"
LVPN_LIBDIR="${LVPN_LIBDIR:-${LVPN_DIR}/lib}"
LVPN_HOSTS="${LVPN_HOSTS:-${LVPN_DIR}/hosts}"
KEYSIZE=${KEYSIZE:-4096}

# Para gettext
TEXTDOMAINDIR=${TEXTDOMAINDIR:-"/usr/share/locale"}
TEXTDOMAIN="$(basename "${LVPN}")"

export TINC LVPN LVPN_DIR LVPN_LIBDIR LVPN_HOSTS KEYSIZE TEXTDOMAINDIR TEXTDOMAIN

. "${LVPN_LIBDIR}/common"

while getopts "h" arg; do
    case $arg in
        h) help lvpn ; exit 0;;
    esac
done
let OPTIND--; shift ${OPTIND}

# El comando
command=$1; shift

# Chequear si el comando existe
if [ ! -x "${LVPN_LIBDIR}/lvpn-${command}" ]; then
    fatal_error "%s no existe, tal vez te gustaría implementarlo :D" ${command}
fi

# Correr el comando
exec ${LVPN_LIBDIR}/lvpn-${command} $@

exit $?
