#!/bin/sh
# Este archivo da de baja las subnets de la VPN

# Solo acepta IPs fuera del rango de LibreVPN
# tinc pasa como SUBNET: MAC, Subnet de la VPN y Subnet extras
# (queremos las extras)
function validate_ip() {
    echo "$1" | \
    grep "[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/[0-9]\+" | \
    egrep -q "192.168.9.[0-9]\+"

    return $?
}

# Agrega una linea al log
function log() {
    echo "$(date) tincd.${NETNAME}[$0]: $@" >> /tmp/subnets.${NETNAME}.log 
}

if validate_ip ${SUBNET}; then
    log "Quitando ruta ${SUBNET} para el nodo ${NODE}"

    if ! which ip; then
        route del ${SUBNET}
    else
        ip route del ${SUBNET}
    fi
fi
