#!/bin/sh
# Este archivo da de baja las subnets de la VPN

# Solo acepta IPs fuera del rango de LibreVPN
# tinc pasa como SUBNET: MAC, Subnet de la VPN y Subnet extras
# (queremos las extras)
# TODO sólo funciona con IPv4

# Si encuentra estas cadenas en la subnet, no es necesario
for not in ':' '192.168.9.'; do
    echo "$SUBNET" | grep "$not" >/dev/null 2>&1
    [ $? -eq 0 ] && exit 0
done

# Usar `ip` si está disponible
which ip >/dev/null && IP=ip

$IP route del $SUBNET dev $INTERFACE
