#!/bin/sh
# Este archivo da de baja la interfaz de la VPN

if which ip &>/dev/null ; then
  ip link set ${INTERFACE} down
else
  ifconfig ${INTERFACE} down
fi

# TODO descomentar cuando tengamos una config por defecto de babeld
# which babeld &>/dev/null && kill $(cat /var/run/babeld.pid)

# TODO no es DRY con respecto a `run-script` pero al menos no tengo que
# escribir código extra :3
export NETNAME NAME DEVICE INTERFACE NODE REMOTEADDRESS REMOTEPORT \
       SUBNET WEIGHT

for _script in /etc/tinc/${NETNAME}/scripts/tinc-*; do
  exec "${_script}" down
done
