#!/bin/bash

# Terminar ante el menor error
set -E
trap_exit() {
    echo "ARGH! Algo pasó" 1>&2
    exit 1
}

trap 'trap_exit' TERM HUP QUIT INT ERR

. "${LVPN_LIBDIR}/msg"

self="$(basename $0)"

# Agrega una linea a un archivo
add_to_file(){
    f=$1; shift

    echo "$@" >>$f
}
