#!/usr/bin/env bash
#
# lib/lvpn-add-subnet
#
# Copyright (c) 2011-2013 LibreVPN <vpn@hackcoop.com.ar>
#
# See AUTHORS for a list of contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#
# Instala un script
# $0 script
# $1 nodo
# $2 evento
# $3 script

. "${LVPN_LIBDIR}"/common

VERBOSE=false
while getopts "vh"; do
  case $arg in
    h) help ${self} ; exit 0;;
    v) VERBOSE=" -v " ;;
  esac
done

node="$(get_node_name "${1}")" ; shift
node_dir="$(get_node_dir "$node")"
event="$(get_event "$1")" ; shift
script="$(get_script "$1")"

test -n "${script}" && fatal_warning "El script %s no existe" "${script##*/}"
test -n "${node}"   && fatal_warning "El nodo %s no existe" "${node}"
test -n "${event}"  && fatal_warning "El evento %s no es válido" "${event}"

# Instalar run-script para este evento
for _state in up down; do
  test ! -f "${node_dir}/${event}-${_state}" && \
    cp ${VERBOSE} -f "${LVPN_LIBDIR}/skel/run-script" \
                     "${node_dir}/${event}-${_state}"
done

# Instalar el script para el evento
cp ${VERBOSE} -f "${script}" "${node_dir}/scripts/${event}-${script##*/}"
