#!/bin/bash
# Sincroniza los nodos de un nodo remoto o local
# Necesita acceso SSH, pensado para sincronizar nodos en un router con *WRT
# No usamos rsync porque no existe

. "${LVPN_LIBDIR}"/common

requires ssh scp 

while getopts "h" arg; do
    case $arg in
        h) help ${self} ; exit 0;;
    esac
done
let OPTIND--; shift ${OPTIND}

# Setear las opciones
node="$1"; shift
host="$1"; shift
dir="$1"; shift

nodedir="${LVPN_DIR}/nodos/${node}"

if [ ! -f "${nodedir}/tinc.conf" ]; then
    fatal_error "El nodo no existe o es inválido"
fi

# Crear el directorio
ssh ${host} mkdir -p "${dir:-${TINC}}/"
# Usamos un scp normal porque probablemente no haya rsync del otro lado
# scp normalmente pisa todos los archivos
scp -r "${nodedir}" ${host}:"${dir:-${TINC}}/"

exit $?
