#!/usr/bin/env bash
# Sincroniza los nodos de un nodo remoto o local
# Necesita acceso SSH, pensado para sincronizar nodos en un router con *WRT
# No usamos rsync porque no existe

. "${LVPN_LIBDIR}"/common

requires rsync

# Salir si no se es root y no existe sudo, sino usarlo
if [ ! -w / ]; then
  if ! which sudo >/dev/null 2>&1; then
    fatal_error "Correr como root"
  else
    sudo=sudo
  fi
fi

while getopts "hvdn" arg; do
  case $arg in
    h) help ${self} ; exit 0;;
    v) VERBOSE=-v ;;
    n) DRYRUN=--dry-run ;;
    d) DELETE=--delete-after ;;
  esac
done
let OPTIND--; shift ${OPTIND}

nodedir="$(get_node_dir "${1}")"

msg "Instalando en el sistema..."
$sudo mkdir -p "${TINC}"
$sudo rsync -a --no-owner --no-group ${VERBOSE} ${DELETE} ${DRYRUN} "${nodedir}/" "${TINC}/"

# Habilitar tinc en el sistema
find_init_system | while read init_system init_file; do
  case $init_system in
    deb)
      grep -q ${NETWORK} "${init_file}" || \
      $sudo sh -c "echo ${NETWORK} >>${init_file}"

# Habilitar el log y cambiar a un usuario sin privilegios
      grep -q "^EXTRA=" /etc/default/tinc || \
      $sudo sh -c "echo 'EXTRA=\"${TINCD_FLAGS}\"' >>/etc/default/tinc"
      ;;
    systemd)
# Instalar el .service desde el skel
      $sudo sed "s/{{TINCD_FLAGS}}/${TINCD_FLAGS}/g" \
                ${LVPN_LIBDIR}/skel/tincd@.service \
                >${init_file}
      ;;
    unknown)
      warning "Tu sistema de inicio de tinc es desconocido, tenés que habilitar el demonio a mano o reportar un bug :)" ;;
  esac
done

# Agregar avahi en nsswitch.conf
if [ -f /lib/libnss_mdns.so.2 ]; then
  grep -q "mdns" /etc/nsswitch.conf } || \
  $sudo sed -e "s/^hosts:.*$/#&\nhosts: files mdns_minimal [NOTFOUND=return] dns mdns/" \
            -i /etc/nsswitch.conf
else
  warning "Es necesario instalar nss-mdns para poder resolver nombres .local"
fi

$sudo which avahi-daemon &>/dev/null || \
  warning "Se recomienda instalar avahi-daemon"

exit $?
