#!/usr/bin/env bash
#
# lib/lvpn-add-keynode
#
# Copyright (c) 2011-2013 LibreVPN <vpn@hackcoop.com.ar>
#
# See AUTHORS for a list of contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#
# Agrega un nodo servidor de llaves

. "${LVPN_LIBDIR}"/common

requires git

LIST=false
UPDATE=false
while getopts "hlu" arg; do
  case $arg in
    h) help ${self} ; exit 0;;
    l) LIST=true ;;
    u) UPDATE=true ;;
  esac
done
let OPTIND--; shift ${OPTIND}

node="$(get_node_name "${1}")"
nodedir="$(get_node_dir "${1}")"
keynodedir="$(get_keynode_dir "${1}")"; shift

if ${LIST}; then
  if test -d "${keynodedir}" && ! test -d "${keynodedir}/.git"; then
    warning "El nodo %s todavía no tiene nodos llavero configurados" "${node}"
  else
    silent pushd "${keynodedir}"
    git remote -v \
    | cut -d" " -f1 \
    | column -t \
    | sort -u
  fi

  exit 0
fi

if ${UPDATE}; then
  silent pushd "${keynodedir}"

  # Comitea todos nuestros cambios
  git commit -am "${node}: keynode upgrade" || true

  _cur_branch="$(git rev-parse --abbrev-ref HEAD)"
  # Recorre todos los repos trayendo los cambios
  git remote -v | grep "(fetch)$" | cut -f1 \
  | while read _remote; do
    git pull --rebase "${_remote}" "${_cur_branch}" || true
  done

  # y subiendo los nuestros
  git remote -v | grep "(push)$" | cut -f1 \
  | while read _remote; do
    git push "${_remote}" "${_cur_branch}" || true
  done

  exit 0
fi

# Si el directorio de llaves no es un repositorio git, eliminarlo
if test -d "${keynodedir}" && ! test -d "${keynodedir}/.git"; then
  mv "${keynodedir}"{,~}
fi

# Por cada repositorio, clonar el primero y agregar el resto como
# remotes
for repo in $@; do
  if ! test -d "${keynodedir}/.git" ; then
    msg "Clonando hosts.git"
    git clone "${repo}" "${keynodedir}"
    continue
  fi

  silent pushd "${keynodedir}"

  if git remote -v | cut -f2 | grep -q "${repo}" ; then
    warning "Ignorando el repositorio duplicado %s" "${repo}"
    continue
  fi

  # convierte
  # ssh://lvpn-keynode@192.168.9.3:49001/pub/hosts.git
  # en 
  # 192.168.9.3
  _remote="$(echo "${repo}" | cut -d@ -f2 | cut -d: -f1)"
  git remote add "${_remote}" "${repo}"
done

