#!/usr/bin/env bash
# Agrega valores connectto a un nodo

. "${LVPN_LIBDIR}"/common

while getopts "h" arg; do
    case $arg in
        h) help ${self} ; exit 0;;
    esac
done
let OPTIND--; shift ${OPTIND}

node="$(get_node_name "$1")"; shift
hosts="$@"

nodedir="$(get_node_dir ${node})"

# Salir si hosts está vacío
if [ -z "${hosts}" ]; then exit; fi

# Agregar los nodos
${LVPN} add-host ${node} ${hosts} || \
    fatal_error "No se pudieron agregar los archivos de host"

# Recorrer todos los host que se pasaron
for _connectto in ${hosts}; do
  if ! grep -q "^Address" "$(get_node_file ${_connectto})"; then
    warning "El nodo %s no tiene una ubicación pública, no será posible conectarse" ${_connectto}
    continue
  fi

# No es necesario agregarlo dos veces
  grep -q "^ConnectTo = ${_connectto}$" && continue

# Agregar la linea ConnectTo = nodo a tinc.conf
  msg "Conectar a %s" "${_connectto}"
  add_to_file "${nodedir}/tinc.conf" "ConnectTo = ${_connectto}"
done

exit $?
