#!/bin/bash
# Sincroniza los nodos de un nodo remoto o local
# Necesita acceso SSH, pensado para sincronizar nodos en un router con *WRT
# No usamos rsync porque no existe

. "${LVPN_LIBDIR}"/common

requires rsync

# Salir si no se es root y no existe sudo, sino usarlo
if [ ! -w / ]; then
  if ! which sudo >/dev/null 2>&1; then
    fatal_error "Correr como root"
  else
    sudo=sudo
  fi
fi

while getopts "hvdn" arg; do
  case $arg in
    h) help ${self} ; exit 0;;
    v) VERBOSE=-v ;;
    n) DRYRUN=--dry-run ;;
    d) DELETE=--delete-after ;;
  esac
done
let OPTIND--; shift ${OPTIND}

nodedir="$(get_node_dir "${1}")"

msg "Instalando en el sistema..."
$sudo mkdir -p "${TINC}"
$sudo rsync -a ${VERBOSE} ${DELETE} ${DRYRUN} "${nodedir}/" "${TINC}/"

exit $?
