#!/bin/bash

# La base para todos los mensajes, se imprime en stderr
msg() {
    msg="$1"; shift
    printf "> $msg\n" "$@" 1>&2
}

error() {
    msg="$(gettext "$1")"; shift
    msg "$(gettext "ERROR:") ${msg}" "$@"
}

warning() {
    msg="$(gettext "$1")"; shift
    msg "$(gettext "ALERTA:") ${msg}" "$@"
}

# Mensaje de error y salir
fatal_error() {
    msg="$(gettext "$1")"; shift
    error "${msg}" "$@"
    exit 1
}

# Toma la ayuda desde doc/$comando
# $1 el comando para obtener la ayuda
help() {
    ${PAGER:-less -niSFX} "${LVPN_DIR}/doc/$1.markdown" 2>/dev/null || true
}

# Obtiene la id del responsable del nodo
get_id() {
    if which git >/dev/null; then
        echo "# $(git config --get user.name) <$(git config --get user.email)>"
    else
        echo "# $USER@$HOSTNAME"
    fi
}
