.TH "LVPN\-INSTALL\-MAIL\-SERVER" "1" "2013" "Manual de LibreVPN" "lvpn"
.SH NOMBRE
.PP
\f[I]lvpn install\-mail\-server\f[] instala un servidor de correo local
para intercambio de correo electrónico de nodo a nodo.
.SH SINOPSIS
.PP
\f[I]lvpn install\-mail\-server\f[] [\-h] [\-f] [\-p /etc/postfix]
nodo\-local
.SH DESCRIPCION
.PP
Instala una configuración de \f[I]postfix\f[] orientada a intercambiar
correo electrónico entre nodos usando direcciones locales con la forma
\f[I]usuario\@nodo.local\f[].
Además puede enviar correo hacia Internet usando un gateway SMTP que
traduce las direcciones.
.SH OPCIONES
.TP
.B \-h
Este mensaje
.RS
.RE
.TP
.B \-f
Forzar la instalación, eliminando la configuración de postfix existente
.RS
.RE
.TP
.B \-p /etc/postfix
Instala la configuración en otra ruta.
.RS
.RE
.SH VER TAMBIEN
.PP
\f[I]postfix(1)\f[] \f[I]postmap(1)\f[] \f[I]transport(5)\f[]
.SH AUTHORS
Nicolás Reynolds <fauno@endefensadelsl.org>.
