.TH LVPN\-D3 1 "2013" "Manual de LibreVPN" "lvpn"
.SH NOMBRE
.PP
Exportar los enlaces y nodos a un gráfico de fuerza con d3.js.
.SH SINOPSIS
.PP
lvpn d3 > data.json
.SH DESCRIPCION
.PP
Extrae los nodos y enlaces conocidos del log de tincd y los imprime en
JSON para D3.
.PP
El daemon tincd debe iniciarse con \f[I]\-\-logfile\f[].
.SH AUTHORS
Nicolás Reynolds <fauno@endefensadelsl.org>.
