.TH "LVPN\-AVAHI\-ANUNCIO.MARKDOWN" "1" "2013" "Manual de LibreVPN" "lvpn"
.SH lvpn\-announce
.PP
Anunciar la llave en la red local usando avahi.
.PP
\-h Este mensaje
.PP
Uso:
.IP \[bu] 2
Anunciar un nodo
.PP
lvpn avahi\-anuncio nodo [tcp|udp] puerto archivo
.SH AUTHORS
Nicolás Reynolds <fauno@endefensadelsl.org>.
