.TH LVPN\-D3 1 "2013" "Manual de LibreVPN" "lvpn"
.SH NAME
.PP
Export links and nodes to a d3js force graph.
.SH SYNOPSIS
.PP
lvpn d3 > data.json
.SH DESCRIPTION
.PP
Extracts known nodes and links from the tincd log and prints them in
JSON format for D3.
.PP
Tincd must be started with \f[I]\-\-logfile\f[].
.SH AUTHORS
Nicolás Reynolds <fauno@endefensadelsl.org>.
