.TH "LVPN\-INSTALL\-SCRIPT" "1" "2013" "LibreVPN Manual" "LibreVPN"
.SH NAME
.PP
lvpn install\-script install a script thats executed during VPN events.
.SH SYNOPSIS
.PP
lvpn install\-script [\-hves] local\-node event script
.SH DESCRIPTION
.PP
Installs scripts to be executed on VPN events.
At the moment, \f[C]tincd\f[] only supports two kinds of events after
the VPN starts, when a node connects or disconnects, or when a subnet is
announced or dis\-announced.
.SH OPTIONS
.TP
.B \-h
This message
.RS
.RE
.TP
.B \-v
Verbose mode
.RS
.RE
.TP
.B \-e
List available events
.RS
.RE
.TP
.B \-s
List available scripts
.RS
.RE
.SH EVENTS
.TP
.B tinc
This event triggers when the VPN starts/stops.
Put scripts that should run once here.
.RS
.RE
.TP
.B host
Run this script when a node (dis)connects.
.RS
.RE
.TP
.B subnet
Run this script when a subnet becomes (un)reachable
.RS
.RE
.SH SCRIPTS
.TP
.B debug
Debug events
.RS
.RE
.TP
.B notify
Show a notification using D\-Bus.
\f[B]It doesn\[aq]t work\f[] because D\-Bus doesn\[aq]t allow users to
send notification to another user\[aq]s session.
.RS
.RE
.TP
.B ipv6\-router
Set this node as an IPv6 router/gateway.
.RS
.RE
.TP
.B ipv6\-default\-route
Set this node\[aq]s IPv6 default route.
.RS
.RE
.SH EXAMPLES
.SS Notify when a host (dis)connects
.PP
\f[I]lvpn install\-script\f[] ponape host notify
.SH SEE ALSO
.PP
\f[I]tinc.conf(5)\f[]
.SH AUTHORS
Nicolás Reynolds <fauno@endefensadelsl.org>.
